# Generated by Django 3.2.7 on 2021-09-17 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='unique',
        ),
    ]
