# Generated by Django 3.2.7 on 2021-09-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_remove_day_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
