# Generated by Django 3.2.7 on 2021-09-17 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_alter_fooditem_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='foods.food'),
        ),
    ]
