# Generated by Django 3.2.7 on 2021-09-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_alter_fooditem_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food',
            field=models.CharField(default='vegetables', max_length=20),
        ),
    ]
