# Generated by Django 3.2.7 on 2021-09-17 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_alter_fooditem_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='foods.food'),
        ),
    ]
