# Generated by Django 3.2.7 on 2021-09-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_alter_fooditem_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='date_for_search',
            field=models.IntegerField(default=0),
        ),
    ]
