# Generated by Django 3.2.7 on 2021-09-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_fooditem_date_for_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='date_for_search',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
