# Generated by Django 3.2.7 on 2021-09-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0009_dailycalorieintake'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.URLField(blank=True, max_length=150),
        ),
    ]
