# Generated by Django 3.2.7 on 2021-10-09 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0012_dailycalorieintake_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyCalorieIntake',
        ),
    ]
